### ISSUE TITLE
Activate Doctests

### ISSUE THREAD

**Issue by SebastianJL** [Phynix/uniphy#14]
Basically we test our project with unittests. Still it is often good practice to supply examples in docstrings. These could be automatically tested with doctests if they are written in the doctest format.

**Comment by jonas-eschle** [comment]
I agree. Most of all it is nice for the user to see working examples and doctest basically assures that the examples will work. I will add this after the type_checked merge

**Comment by jonas-eschle** [comment]
Doctests work but I had some regex problem setting it up to test for arbitrary deeply nested repos, so I keep this open and retry once.

**Comment by SebastianJL** [comment]
I will still close. We can reopen when needed.
